"""Standalone q execution and portable KX results for IPython/Jupyter."""

from .config import (
    Config,
    ConfigError,
    Profile,
    config_path,
    load_config,
    resolve_password,
    save_config,
)
from .contract import (
    CONTRACT_VERSION,
    DEFAULT_BYTE_LIMIT,
    DEFAULT_ROW_LIMIT,
    MIME_TYPE,
    Chart,
    EvaluationResult,
    KxNotebookError,
    OutputLimitError,
    PortableOutput,
    QText,
    TableShapeError,
    build_mime_bundle,
)
from .display import display_result
from .evaluators import (
    BrokerEvaluator,
    CallbackEvaluator,
    DirectQEvaluator,
    EvaluationContext,
    Evaluator,
    EvaluatorError,
    PyKXEvaluator,
)
from .ipc import (
    QCancelledError,
    QChar,
    QCharVector,
    QConnection,
    QDictionary,
    QError,
    QIpcError,
    QKeyedTable,
    QSymbol,
    QTable,
    QTemporal,
    QTimeoutError,
)
from .magic import (
    clear_evaluator,
    configure_evaluator,
    load_ipython_extension,
    unload_ipython_extension,
)
from .testing import FixtureEvaluator

__version__ = "0.1.0"

__all__ = [
    "CONTRACT_VERSION",
    "DEFAULT_BYTE_LIMIT",
    "DEFAULT_ROW_LIMIT",
    "MIME_TYPE",
    "BrokerEvaluator",
    "CallbackEvaluator",
    "Chart",
    "Config",
    "ConfigError",
    "DirectQEvaluator",
    "EvaluationContext",
    "EvaluationResult",
    "Evaluator",
    "EvaluatorError",
    "FixtureEvaluator",
    "KxNotebookError",
    "OutputLimitError",
    "PortableOutput",
    "Profile",
    "PyKXEvaluator",
    "QCancelledError",
    "QChar",
    "QCharVector",
    "QConnection",
    "QDictionary",
    "QError",
    "QIpcError",
    "QKeyedTable",
    "QTable",
    "QTemporal",
    "QText",
    "QTimeoutError",
    "QSymbol",
    "TableShapeError",
    "__version__",
    "build_mime_bundle",
    "clear_evaluator",
    "config_path",
    "configure_evaluator",
    "display_result",
    "load_config",
    "load_ipython_extension",
    "resolve_password",
    "save_config",
    "unload_ipython_extension",
]
